AWSTemplateFormatVersion: "2010-09-09"

Description:  This nested stack template deploys a VPC, with a public and private subnets,ALB in public Subnet and ASG in Private Subnet with all the necessary supporting resources

Parameters:
  VpcBlock:
    Type: String
    Default: 192.168.0.0/16
    AllowedPattern: '.+'
    Description: The CIDR range for the VPC. This should be a valid private (RFC 1918) CIDR range.

  PrivateSubnet01Block:
    Type: String
    Default: 192.168.64.0/19
    AllowedPattern: '.+'
    Description: CidrBlock for private subnet 01 within the VPC

  PrivateSubnet02Block:
    Type: String
    Default: 192.168.96.0/19
    AllowedPattern: '.+'
    Description: CidrBlock for private subnet 02 within the VPC

  PrivateSubnet03Block:
    Type: String
    Default: 192.168.128.0/19
    AllowedPattern: '.+'
    Description: CidrBlock for private subnet 03 within the VPC

 
  PublicSubnet01Block:
    Type: String
    Default: 192.168.160.0/19
    AllowedPattern: '.+'
    Description: CidrBlock for public subnet 01 within the VPC
  
  PublicSubnet02Block:
    Type: String
    Default: 192.168.192.0/19
    AllowedPattern: '.+'
    Description: CidrBlock for public subnet 02 within the VPC
  
  PublicSubnet03Block:
    Type: String
    Default: 192.168.224.0/19
    AllowedPattern: '.+'
    Description: CidrBlock for public subnet 03 within the VPC
    
  MapPublicIpOnLaunch:
    Type: String
    Default: true
    AllowedPattern: '.+'
    Description: Indicates whether instances launched in this subnet receive a public IPv4 address
    
  LoadBalancerName:
    Type: String
    Default: ASGLoadbalancer
    Description: Name of the loadbalancer which will point to ASG instances in private subnet
    
  NodeAutoScalingGroupDesiredCapacity:
    Type: Number
    Default: 2
    Description: Desired capacity of Node Group ASG.

  NodeAutoScalingGroupMaxSize:
    Type: Number
    Default: 4
    Description: Maximum size of Node Group ASG. Set to at least 1 greater than NodeAutoScalingGroupDesiredCapacity.

  NodeAutoScalingGroupMinSize:
    Type: Number
    Default: 1
    Description: Minimum size of Node Group ASG.

  DisableIMDSv1:
    Type: String
    Default: "false"
    AllowedValues:
      - "false"
      - "true"

  NodeInstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.large
      - t3.medium
      - t3.micro
      - t3.nano
      - t3.small
      - t3.xlarge
    ConstraintDescription: Must be a valid EC2 instance type
    Description: EC2 instance type for the node instances

  NodeVolumeSize:
    Type: Number
    Default: 20
    Description: Node volume size
    
  NodeImageId:
    Type: "String"
    Default: ami-047a51fa27710816e
    Description: Latest Amazon Linux2 ami-id

  deploybucketname:
    Type: String
    Default: apachedeploymcasg
    Description: The S3 bucket used to store the deployment scripts for userdata

  KeyName:
   Type: "AWS::EC2::KeyPair::KeyName"
   Description: The EC2 Key Pair to allow SSH access to the instances

Resources: 
  NetworkStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://master-card-assignment-cloudformation.s3.amazonaws.com/network_stack.yaml
      Parameters: 
        VpcBlock: !Ref VpcBlock
        PrivateSubnet01Block: !Ref PrivateSubnet01Block
        PrivateSubnet02Block: !Ref PrivateSubnet02Block
        PrivateSubnet03Block: !Ref PrivateSubnet03Block
        PublicSubnet01Block: !Ref PublicSubnet01Block
        PublicSubnet02Block: !Ref PublicSubnet02Block
        PublicSubnet03Block: !Ref PublicSubnet03Block
        MapPublicIpOnLaunch: !Ref MapPublicIpOnLaunch
        LoadBalancerName: !Ref LoadBalancerName
        
  IAMGovernanceStack: 
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties: 
      TemplateURL: https://master-card-assignment-cloudformation.s3.amazonaws.com/IAM_Governance_Stack.yaml
      
  ComputeStack: 
    Type: AWS::CloudFormation::Stack
    DependsOn: [NetworkStack,IAMGovernanceStack]
    Properties: 
      TemplateURL: https://master-card-assignment-cloudformation.s3.amazonaws.com/compute_stack.yaml
      Parameters: 
        NodeAutoScalingGroupDesiredCapacity: !Ref NodeAutoScalingGroupDesiredCapacity
        NodeAutoScalingGroupMaxSize: !Ref NodeAutoScalingGroupMaxSize
        NodeAutoScalingGroupMinSize: !Ref NodeAutoScalingGroupMinSize
        DisableIMDSv1: !Ref DisableIMDSv1
        NodeInstanceType: !Ref NodeInstanceType
        NodeVolumeSize: !Ref NodeVolumeSize
        NodeImageId: !Ref NodeImageId
        deploybucketname: !Ref deploybucketname
        Subnets: !GetAtt NetworkStack.Outputs.PrivateSubnetIds
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        SecurityGroup: !GetAtt NetworkStack.Outputs.SecurityGroups
        InstanceProfile: !GetAtt IAMGovernanceStack.Outputs.NodeInstanceProfile
        TargetGroup: !GetAtt NetworkStack.Outputs.TargetGroupName
        KeyName: !Ref KeyName
  